# Generated by Django 4.2.20 on 2025-04-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_product_todoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootcauseanalysis',
            name='failure_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rootcauseanalysis',
            name='impact_severity',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='rootcauseanalysis',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='rootcauseanalysis',
            name='time_to_detect_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SelfHealAttempt',
        ),
    ]
