# Generated by Django 5.2 on 2025-04-26 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_rootcauseanalysis_affected_components_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootcauseanalysis',
            name='api_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_cause_analyses', to='playground.apiresponse'),
        ),
        migrations.AlterField(
            model_name='rootcauseanalysis',
            name='chaos_test_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_cause_analyses', to='playground.chaostestrun'),
        ),
    ]
